// Mocks generated by Mockito 5.4.5 from annotations
// in learning_pwa/test/progress_sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:learning_pwa/models/concept.dart' as _i7;
import 'package:learning_pwa/models/lesson.dart' as _i4;
import 'package:learning_pwa/models/lesson_progress.dart' as _i6;
import 'package:learning_pwa/models/local_lesson.dart' as _i5;
import 'package:learning_pwa/models/mcq.dart' as _i8;
import 'package:learning_pwa/services/hive_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i2.HiveService {
  MockHiveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheLesson(_i4.Lesson? lesson) => (super.noSuchMethod(
        Invocation.method(
          #cacheLesson,
          [lesson],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Lesson>> getOfflineLessons(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfflineLessons,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.Lesson>>.value(<_i4.Lesson>[]),
      ) as _i3.Future<List<_i4.Lesson>>);

  @override
  _i3.Future<bool> isLessonOffline(String? lessonId) => (super.noSuchMethod(
        Invocation.method(
          #isLessonOffline,
          [lessonId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteLessonOffline(String? lessonId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLessonOffline,
          [lessonId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearOfflineLessons() => (super.noSuchMethod(
        Invocation.method(
          #clearOfflineLessons,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheLessons(List<_i4.Lesson>? lessons) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheLessons,
          [lessons],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.Lesson?> getLesson(String? lessonId) => (super.noSuchMethod(
        Invocation.method(
          #getLesson,
          [lessonId],
        ),
        returnValue: _i3.Future<_i4.Lesson?>.value(),
      ) as _i3.Future<_i4.Lesson?>);

  @override
  _i3.Future<List<_i4.Lesson>> getAllLessons() => (super.noSuchMethod(
        Invocation.method(
          #getAllLessons,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Lesson>>.value(<_i4.Lesson>[]),
      ) as _i3.Future<List<_i4.Lesson>>);

  @override
  _i3.Future<List<_i4.Lesson>> searchLessons(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchLessons,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.Lesson>>.value(<_i4.Lesson>[]),
      ) as _i3.Future<List<_i4.Lesson>>);

  @override
  _i3.Future<void> saveLesson(_i4.Lesson? lesson) => (super.noSuchMethod(
        Invocation.method(
          #saveLesson,
          [lesson],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheLocalLesson(_i5.LocalLesson? lesson) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheLocalLesson,
          [lesson],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.LocalLesson>> getLocalLessons(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalLessons,
          [userId],
        ),
        returnValue:
            _i3.Future<List<_i5.LocalLesson>>.value(<_i5.LocalLesson>[]),
      ) as _i3.Future<List<_i5.LocalLesson>>);

  @override
  _i3.Future<_i5.LocalLesson?> getLocalLesson(String? lessonId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalLesson,
          [lessonId],
        ),
        returnValue: _i3.Future<_i5.LocalLesson?>.value(),
      ) as _i3.Future<_i5.LocalLesson?>);

  @override
  _i3.Future<void> deleteLocalLesson(String? lessonId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLocalLesson,
          [lessonId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveProgress(_i6.UserProgress? progress) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProgress,
          [progress],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheConcept(_i7.Concept? concept) => (super.noSuchMethod(
        Invocation.method(
          #cacheConcept,
          [concept],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheConcepts(List<_i7.Concept>? concepts) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheConcepts,
          [concepts],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i7.Concept?> getConcept(String? conceptId) => (super.noSuchMethod(
        Invocation.method(
          #getConcept,
          [conceptId],
        ),
        returnValue: _i3.Future<_i7.Concept?>.value(),
      ) as _i3.Future<_i7.Concept?>);

  @override
  _i3.Future<List<_i7.Concept>> getConceptsByLesson(String? lessonId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConceptsByLesson,
          [lessonId],
        ),
        returnValue: _i3.Future<List<_i7.Concept>>.value(<_i7.Concept>[]),
      ) as _i3.Future<List<_i7.Concept>>);

  @override
  _i3.Future<void> cacheMcq(_i8.Mcq? mcq) => (super.noSuchMethod(
        Invocation.method(
          #cacheMcq,
          [mcq],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheMcqs(List<_i8.Mcq>? mcqs) => (super.noSuchMethod(
        Invocation.method(
          #cacheMcqs,
          [mcqs],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i8.Mcq?> getMcq(String? mcqId) => (super.noSuchMethod(
        Invocation.method(
          #getMcq,
          [mcqId],
        ),
        returnValue: _i3.Future<_i8.Mcq?>.value(),
      ) as _i3.Future<_i8.Mcq?>);

  @override
  _i3.Future<List<_i8.Mcq>> getMcqsByLesson(String? lessonId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMcqsByLesson,
          [lessonId],
        ),
        returnValue: _i3.Future<List<_i8.Mcq>>.value(<_i8.Mcq>[]),
      ) as _i3.Future<List<_i8.Mcq>>);

  @override
  _i3.Future<void> cacheProgress(_i6.UserProgress? progress) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProgress,
          [progress],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.UserProgress>> getProgress() => (super.noSuchMethod(
        Invocation.method(
          #getProgress,
          [],
        ),
        returnValue:
            _i3.Future<List<_i6.UserProgress>>.value(<_i6.UserProgress>[]),
      ) as _i3.Future<List<_i6.UserProgress>>);

  @override
  _i3.Future<List<_i6.UserProgress>> getUnsyncedProgress() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedProgress,
          [],
        ),
        returnValue:
            _i3.Future<List<_i6.UserProgress>>.value(<_i6.UserProgress>[]),
      ) as _i3.Future<List<_i6.UserProgress>>);

  @override
  _i3.Future<void> markProgressAsSynced(List<String>? progressIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #markProgressAsSynced,
          [progressIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearProgress() => (super.noSuchMethod(
        Invocation.method(
          #clearProgress,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
