// Mocks generated by Mockito 5.4.5 from annotations
// in learning_pwa/test/providers/hands_free_settings_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:learning_pwa/models/hands_free_settings.dart' as _i2;
import 'package:learning_pwa/services/hands_free_settings_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHandsFreeSettings_0 extends _i1.SmartFake
    implements _i2.HandsFreeSettings {
  _FakeHandsFreeSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HandsFreeSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHandsFreeSettingsService extends _i1.Mock
    implements _i3.HandsFreeSettingsService {
  MockHandsFreeSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.HandsFreeSettings> get settingsStream => (super.noSuchMethod(
        Invocation.getter(#settingsStream),
        returnValue: _i4.Stream<_i2.HandsFreeSettings>.empty(),
      ) as _i4.Stream<_i2.HandsFreeSettings>);

  @override
  _i4.Stream<bool> get stateStream => (super.noSuchMethod(
        Invocation.getter(#stateStream),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i2.HandsFreeSettings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeHandsFreeSettings_0(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i2.HandsFreeSettings);

  @override
  bool get isHandsFreeEnabled => (super.noSuchMethod(
        Invocation.getter(#isHandsFreeEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveSettings(_i2.HandsFreeSettings? newSettings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [newSettings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveState(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #saveState,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateSetting<T>(
    String? settingName,
    T? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSetting,
          [
            settingName,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleEnabled() => (super.noSuchMethod(
        Invocation.method(
          #toggleEnabled,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> enable() => (super.noSuchMethod(
        Invocation.method(
          #enable,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> disable() => (super.noSuchMethod(
        Invocation.method(
          #disable,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool shouldAutoEnable() => (super.noSuchMethod(
        Invocation.method(
          #shouldAutoEnable,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.HandsFreeSettings getRecommendedSettings() => (super.noSuchMethod(
        Invocation.method(
          #getRecommendedSettings,
          [],
        ),
        returnValue: _FakeHandsFreeSettings_0(
          this,
          Invocation.method(
            #getRecommendedSettings,
            [],
          ),
        ),
      ) as _i2.HandsFreeSettings);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
