// Mocks generated by Mockito 5.4.5 from annotations
// in learning_pwa/test/services/global_voice_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:learning_pwa/models/audio_state.dart' as _i4;
import 'package:learning_pwa/models/voice_command.dart' as _i5;
import 'package:learning_pwa/services/voice_input_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [VoiceInputService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceInputService extends _i1.Mock implements _i2.VoiceInputService {
  MockVoiceInputService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.AudioState> get stateStream => (super.noSuchMethod(
        Invocation.getter(#stateStream),
        returnValue: _i3.Stream<_i4.AudioState>.empty(),
      ) as _i3.Stream<_i4.AudioState>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get hasPermissions => (super.noSuchMethod(
        Invocation.getter(#hasPermissions),
        returnValue: false,
      ) as bool);

  @override
  bool get canListen => (super.noSuchMethod(
        Invocation.getter(#canListen),
        returnValue: false,
      ) as bool);

  @override
  _i4.VoiceInputState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _i4.VoiceInputState.idle,
      ) as _i4.VoiceInputState);

  @override
  double get confidence => (super.noSuchMethod(
        Invocation.getter(#confidence),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isListening => (super.noSuchMethod(
        Invocation.getter(#isListening),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> get capabilities => (super.noSuchMethod(
        Invocation.getter(#capabilities),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get isManualInputMode => (super.noSuchMethod(
        Invocation.getter(#isManualInputMode),
        returnValue: false,
      ) as bool);

  @override
  List<String> get statusLog => (super.noSuchMethod(
        Invocation.getter(#statusLog),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> checkPermissions() => (super.noSuchMethod(
        Invocation.method(
          #checkPermissions,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> startListening({
    String? localeId,
    Duration? listenFor,
    Duration? pauseFor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startListening,
          [],
          {
            #localeId: localeId,
            #listenFor: listenFor,
            #pauseFor: pauseFor,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> stopListening() => (super.noSuchMethod(
        Invocation.method(
          #stopListening,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancel() => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.VoiceCommand?> listenForCommand({
    Duration? timeout,
    String? localeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenForCommand,
          [],
          {
            #timeout: timeout,
            #localeId: localeId,
          },
        ),
        returnValue: _i3.Future<_i5.VoiceCommand?>.value(),
      ) as _i3.Future<_i5.VoiceCommand?>);

  @override
  void submitManualInput(String? input) => super.noSuchMethod(
        Invocation.method(
          #submitManualInput,
          [input],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<String?> waitForManualInput() => (super.noSuchMethod(
        Invocation.method(
          #waitForManualInput,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  List<String> getAvailableLocales() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableLocales,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> getSetupInstructions() => (super.noSuchMethod(
        Invocation.method(
          #getSetupInstructions,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  Map<String, String> getCommandMappings() => (super.noSuchMethod(
        Invocation.method(
          #getCommandMappings,
          [],
        ),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i3.Future<bool> fallbackToNextProvider() => (super.noSuchMethod(
        Invocation.method(
          #fallbackToNextProvider,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void setPermissionGranted(bool? granted) => super.noSuchMethod(
        Invocation.method(
          #setPermissionGranted,
          [granted],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRecognizedTextForTesting(String? text) => super.noSuchMethod(
        Invocation.method(
          #setRecognizedTextForTesting,
          [text],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
