import '../user_concept_state.dart';

enum DomainEvidenceLevel {
  strongEvidence,
  moderateEvidence,
  needsReinforcement;

  String get displayName {
    switch (this) {
      case DomainEvidenceLevel.strongEvidence:
        return 'Strong Evidence';
      case DomainEvidenceLevel.moderateEvidence:
        return 'Moderate Evidence';
      case DomainEvidenceLevel.needsReinforcement:
        return 'Needs Reinforcement';
    }
  }

  static DomainEvidenceLevel fromPercentage(double pct) {
    if (pct >= 80.0) return DomainEvidenceLevel.strongEvidence;
    if (pct >= 65.0) return DomainEvidenceLevel.moderateEvidence;
    return DomainEvidenceLevel.needsReinforcement;
  }
}

/// Official published parameters directly from the authoritative examination blueprint.
/// (Section 15.6: Kept strictly distinct from app estimates)
class OfficialExamFacts {
  final String examCode;
  final String title;
  final int publishedPassingScore;
  final String scoreScale; // e.g. "100-900"
  final int timeLimitMinutes;
  final String nonAffiliationNotice;

  const OfficialExamFacts({
    required this.examCode,
    required this.title,
    required this.publishedPassingScore,
    required this.scoreScale,
    required this.timeLimitMinutes,
    this.nonAffiliationNotice =
        'All trademarks and examination names are the property of their respective owners. Standards shown for educational alignment only.',
  });
}

/// Statistical readiness projection generated by the application.
/// (Section 15.6: Uses evidence-based framing, strictly avoiding overclaiming "Mastered")
class AppReadinessEstimate {
  final double practiceScorePercentage; // 0.0 to 100.0
  final int estimatedScaledScore; // e.g. 770 on 100-900 scale
  final TargetReadinessBand readinessBand;
  final String readinessHeadline;
  final String readinessSummary;
  final int totalQuestions;
  final int correctCount;
  final int partialCount;
  final int incorrectCount;
  final int unansweredCount;
  final double totalScoreEarned;

  const AppReadinessEstimate({
    required this.practiceScorePercentage,
    required this.estimatedScaledScore,
    required this.readinessBand,
    required this.readinessHeadline,
    required this.readinessSummary,
    required this.totalQuestions,
    required this.correctCount,
    required this.partialCount,
    required this.incorrectCount,
    required this.unansweredCount,
    required this.totalScoreEarned,
  });

  bool get indicatesPassingReadiness =>
      readinessBand == TargetReadinessBand.strongCoverage || practiceScorePercentage >= 80.0;
}

/// Domain-level performance diagnostic adhering to evidence-based terminology.
class DomainDiagnostic {
  final String domainId;
  final String domainCode;
  final String domainTitle;
  final double domainWeight; // Blueprint weight, e.g. 0.12 (12%)
  final int totalQuestions;
  final int correctQuestions;
  final double scoreEarned;
  final double percentage; // 0.0 to 100.0
  final DomainEvidenceLevel evidenceLevel;

  const DomainDiagnostic({
    required this.domainId,
    required this.domainCode,
    required this.domainTitle,
    required this.domainWeight,
    required this.totalQuestions,
    required this.correctQuestions,
    required this.scoreEarned,
    required this.percentage,
    required this.evidenceLevel,
  });
}

/// Specific concept or topic targeted for remediation based on missed questions.
class RemediationRecommendation {
  final String conceptId;
  final String conceptName;
  final String domainTitle;
  final String priority; // 'high', 'medium'
  final String rationale;
  final String? relatedLessonId;

  const RemediationRecommendation({
    required this.conceptId,
    required this.conceptName,
    required this.domainTitle,
    required this.priority,
    required this.rationale,
    this.relatedLessonId,
  });
}

/// Evaluation result for an individual exam question.
class ScoredItemResult {
  final String itemId;
  final String prompt;
  final String domainCode;
  final dynamic userResponse;
  final dynamic correctResponse;
  final bool isCorrect;
  final bool isPartial;
  final double scoreEarned; // 0.0, 0.5, 1.0, etc.
  final String? explanation;
  final List<String> conceptIds;

  const ScoredItemResult({
    required this.itemId,
    required this.prompt,
    required this.domainCode,
    required this.userResponse,
    required this.correctResponse,
    required this.isCorrect,
    this.isPartial = false,
    required this.scoreEarned,
    this.explanation,
    this.conceptIds = const [],
  });
}

/// Complete diagnostic report generated at the completion of a mock exam.
class ExamDiagnosticReport {
  final String sessionId;
  final String targetVersionId;
  final DateTime completedAt;
  final Duration durationTaken;
  final OfficialExamFacts officialFacts;
  final AppReadinessEstimate readinessEstimate;
  final List<DomainDiagnostic> domainDiagnostics;
  final List<RemediationRecommendation> remediationRecommendations;
  final List<ScoredItemResult> scoredItems;

  const ExamDiagnosticReport({
    required this.sessionId,
    required this.targetVersionId,
    required this.completedAt,
    required this.durationTaken,
    required this.officialFacts,
    required this.readinessEstimate,
    required this.domainDiagnostics,
    required this.remediationRecommendations,
    required this.scoredItems,
  });
}
